// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transaction.Models
{
    public partial class account
    {
        public account()
        {
            trandetails = new HashSet<trandetail>();
        }

        public string acnumber { get; set; }
        public string custid { get; set; }
        public string bid { get; set; }
        public decimal? opening_balance { get; set; }
        public DateTime? aod { get; set; }
        public string atype { get; set; }
        public string astatus { get; set; }

        public virtual branch bidNavigation { get; set; }
        public virtual customer cust { get; set; }
        public virtual ICollection<trandetail> trandetails { get; set; }
    }
}