// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transaction.Models
{
    public partial class branch
    {
        public branch()
        {
            accounts = new HashSet<account>();
        }

        public string bid { get; set; }
        public string bname { get; set; }
        public string bcity { get; set; }

        public virtual ICollection<account> accounts { get; set; }
    }
}